-- @Author: kmrocki
-- @Date:   2016-12-14 15:05:55
-- @Last Modified by:   kmrocki
-- @Last Modified time: 2016-12-14 19:07:42

-- Even Fibonacci numbers 
-- 
-- Problem 2 
-- 
-- Each new term in the Fibonacci sequence is
-- generated by adding the previous two terms. By starting with 1 and 2, the
-- first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

fibseq :: (Integral a) => [a] -> a -> [a]
fibseq (a:b:c) x
    | (a < x) = fibseq(a+b:a:b:c) x
    | otherwise = b:c

main = do 
    let solution = sum . filter (even) $ fibseq [1, 0] 4000000
    print solution